{
 "title": "StorageGRID S3 Dashboard",
 "description": "Metrics related to the S3 Protocol",
 "tags": [
  "StorageGRID",
  "S3"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "Site", "label": "Site", "query": "storagegrid_storage_status" },
   { "name": "Node", "label": "Node", "query": "node_cpu_seconds_total" }
  ]
 },
 "panels": [
  {
   "title": "S3 Operations per Second",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "rate(storagegrid_s3_operations_successful{instance=~\"$Node\",site_name=~\"$Site\"}[5m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "S3 Operations per Second (failed)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(storagegrid_s3_operations_failed{instance=~\"$Node\",site_name=~\"$Site\"}[5m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "S3 Operations per Second (unauthorized)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 0 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "rate(storagegrid_s3_operations_unauthorized{instance=~\"$Node\",site_name=~\"$Site\"}[5m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "S3 Upload Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "rate(storagegrid_s3_data_transfers_bytes_ingested{instance=~\"$Node\",site_name=~\"$Site\"}[5m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "S3 Download Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 8 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "rate(storagegrid_s3_data_transfers_bytes_retrieved{instance=~\"$Node\",site_name=~\"$Site\"}[5m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Metadata Query Latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 8 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "sum by (instance) (storagegrid_metadata_queries_average_latency_milliseconds{instance=~\"$Node\",site_name=~\"$Site\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "100 - (avg by (instance) (rate(node_cpu_seconds_total{job=\"node\",mode=\"idle\",instance=~\"$Node\",site_name=~\"$Site\"}[5m])) * 100)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Max Disk Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "max(rate(node_disk_io_time_seconds_total{device=~\"sd[b-q]\",instance=~\"$Node\",site_name=~\"$Site\"}[5m])*100) by (instance) or max(rate(node_disk_io_time_seconds_total{device=~\"dm-[1-9]|dm-1[0-9]|dm-2[0-9]|dm-3[0-9]|dm-4[0-9]|dm-50\",instance=~\"$Node\",site_name=~\"$Site\"}[5m])*100) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Percent Usable Space",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "storagegrid_storage_utilization_usable_space_bytes{instance=~\"$Node\",site_name=~\"$Site\"} / storagegrid_storage_utilization_total_space_bytes{instance=~\"$Node\",site_name=~\"$Site\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Used Storage for Data",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 24 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "storagegrid_storage_utilization_data_bytes",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "S3 and Swift Objects (excluding empty objects)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(storagegrid_content_objects)",
     "legendFormat": "S3 and Swift Objects"
    }
   ]
  },
  {
   "title": "S3 Buckets and Swift Containers",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max(storagegrid_content_buckets_and_containers)",
     "legendFormat": "S3 Buckets and Swift Containers"
    }
   ]
  },
  {
   "title": "ILM Scan Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "storagegrid_ilm_scan_objects_per_second{instance=~\"$Node\",site_name=~\"$Site\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "ILM Awaiting Object Evaluation (incoming from clients)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "storagegrid_ilm_awaiting_client_objects{instance=~\"$Node\",site_name=~\"$Site\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "ILM Awaiting Object Evaluation",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "storagegrid_ilm_awaiting_total_objects{instance=~\"$Node\",site_name=~\"$Site\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}